CREATE TABLE Sitemember (    -- 사이트 회원 테이블 생성 
    uno        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,     -- 사이트 회원 식별번호(기본키,자동생성)
    email      VARCHAR(100) NOT NULL UNIQUE,       -- 이메일(유니크)
    pw         VARCHAR(20) NOT NULL,            -- 비밀번호
    nickname   VARCHAR(40) NOT NULL UNIQUE,      -- 닉네임(유니크)
    name       VARCHAR(20) NOT NULL,               -- 이름
    joindate   DATE DEFAULT CURRENT_DATE,         -- 가입날짜(기본값:현재날짜)
    usertype   NUMBER DEFAULT 1                       -- 유저분류(기본값:1, 기자:2, 운영자:3)
);

-- Webzine 테이블 (웹진 게시글)
CREATE TABLE Webzine (   -- 웹진 테이블 생성
    wno          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,   -- 웹진 고유번호(기본키,자동생성)
    wtitle       VARCHAR(200) NOT NULL,         -- 기사 제목
    wtext        VARCHAR(2000) NOT NULL,        -- 기사 내용
    wwdate       DATE DEFAULT CURRENT_DATE,         -- 기사 작성일
    wviewcount   NUMBER DEFAULT 0,                   -- 조회수
   wofile  VARCHAR(500),               -- 첨부 원본파일명
    wsfile  VARCHAR(500),               -- 첨부 실제 저장파일명
    uno     NUMBER,                               -- 작성자 회원 식별번호(sitemember의 uno을 참조하는 외래 키)
    FOREIGN KEY (uno) REFERENCES Sitemember(uno) ON DELETE SET NULL
);

-- Community 테이블 (커뮤니티 게시글)
CREATE TABLE Community (   -- 게시판 테이블 생성   
    cno         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,    -- 게시글 고유번호(기본키,자동생성)
    ctitle      VARCHAR(100) NOT NULL,        -- 게시글 제목
    ctext       VARCHAR(2000) NOT NULL,         -- 게시글 내용
    cwdate      DATE DEFAULT CURRENT_DATE,      -- 게시글 작성일
    cviewcount  NUMBER DEFAULT 0,               -- 게시글 조회수
    cwuser      VARCHAR(45) NOT NULL,           -- 게시글 작성자(작성시 설정,닉네임 아닌것에 주의)
    cpw         VARCHAR(50) NOT NULL,         --  게시글 비밀번호
    cofile  VARCHAR(500),                        --게시글 첨부 원본파일명
    csfile  VARCHAR(500)                        --게시글 첨부 실제저장파일명
);





//더미 사용자
INSERT INTO SITEMEMBER (UNO,EMAIL,PW,NICKNAME,NAME,USERTYPE)
VALUES(1,'admin1@weekend.kr','1234','운영자','김가윤',3);

INSERT INTO SITEMEMBER (UNO,EMAIL,PW,NICKNAME,NAME,USERTYPE)
VALUES(2,'admin2@weekend.kr','123456','부운영자','홍시원',3);

INSERT INTO SITEMEMBER (UNO,EMAIL,PW,NICKNAME,NAME,USERTYPE)
VALUES(3,'aaa@naver.com','aaa','블로거 지환','오지환',2);

INSERT INTO SITEMEMBER (UNO,EMAIL,PW,NICKNAME,NAME,USERTYPE)
VALUES(4,'bbb@naver.com','bbb','MBC 최지효','최지효',2);

INSERT INTO SITEMEMBER (UNO,EMAIL,PW,NICKNAME,NAME,USERTYPE)
VALUES(5,'ccc@naver.com','ccc','시민기자 임중빈','임중빈',2);

INSERT INTO SITEMEMBER (UNO,EMAIL,PW,NICKNAME,NAME,USERTYPE)
VALUES(6,'ddd@naver.com','ddd','세계문화유산탐방','백송이',2);

//더미 기사
INSERT INTO WEBZINE (WNO,WTITLE,WTEXT,WOFILE,WSFILE,UNO)
VALUES(1,'제주도에서 즐기는 다섯가지 특별한 섬 이야기','제주도에 가면 맛있는 먹거리와 시원한 해안도로를 달려보거나 둘레길을 걷는 즐거움을 가질 수 있다.','JEJU','testimg01.png',1);

INSERT INTO WEBZINE (WNO,WTITLE,WTEXT,WOFILE,WSFILE,UNO)
VALUES(2,'한반도 양 끝에서 만나는 절경! 국내 최북단과 최남단 여행 BEST 4 추천','더미 게시내용입니다.','marado','20250408_1763405.png',2);

INSERT INTO WEBZINE (WNO,WTITLE,WTEXT,WOFILE,WSFILE,UNO)
VALUES(3,'홍콩 여행코스 추천! 빅토리아 피크부터 야시장까지!','더미 게시내용입니다.','hongkong','20250409_142334261.png',3);

INSERT INTO WEBZINE (WNO,WTITLE,WTEXT,WOFILE,WSFILE,UNO)
VALUES(4,'백두산 여름에만 가란 법 있나? 겨울 백두산에서 제대로 설경과 온천 즐겨봐','더미 게시내용입니다.','BAEKDU','20250409_94134335.jpg',4);

INSERT INTO WEBZINE (WNO,WTITLE,WTEXT,WOFILE,WSFILE,UNO)
VALUES(5,'외국인 친구에게 꼭 추천해주고 싶은 지역관광 안테나숍 ''트립집''','더미 게시내용입니다.','TRIPZIP','20250409_12425989.png',5);

INSERT INTO WEBZINE (WNO,WTITLE,WTEXT,WOFILE,WSFILE,UNO)
VALUES(6,'보름씩 떠나는 세계일주 by Parkz 이집트 편','더미 게시내용입니다.','ezypt','20250409_132930212.bmp',6);

commit;

SELECT "KIM"."ISEQ$$_79817".NEXTVAL FROM dual;